```puml
@startuml Account

frame Presentation {
    component [AccountController] as Controller #a7d7fd
}

frame Application {
    component AccountService as Service #a2fdba
}

Controller -(0- Service : IAccountService

frame Infrastructure {
    component [AccountRepository] as Repository #ffa09c
}

Service -(0- Repository : IAccountRepository

frame Domain {
    component Account as Model #fcfdb9  
}

Repository -- Model

@enduml

```